### ISSUE TITLE
feature request: :snowflake: support?

### ISSUE THREAD

**Issue by mklaber** [bluelabsio/records-mover#104]
I can haz Snowflake support? ❄️ 

Point me at what would need to be implemented and I might give it a stab.

**Comment by cwegrzyn** [comment]
:wave:

**Comment by vinceatbluelabs** [comment]
That sounds great to me!

Here's the documentation - improvements welcome: https://github.com/bluelabsio/records-mover/blob/master/docs/DRIVERS.md

Adding full fledged SQL database support in Records Mover requires a reasonable SQLAlchemy driver.   
 I see sqlalchemy-snowflake, so hopefully you're set there.  Even so, generally SQLAlchemy's Dialect API doesn't offer 100% of what we need in terms of metadata, so that doc will guide you through adding a Records Mover-specific driver on top of it.

Here's an example of what we needed for PostgreSQL: https://github.com/bluelabsio/records-mover/blob/master/records_mover/db/postgres/postgres_db_driver.py

Happy to talk more--let me know what you need!
