### ISSUE TITLE
Spec ambiguity with fractional seconds

### ISSUE THREAD

**Issue by vinceatbluelabs** [bluelabsio/records-mover#157]
The Records Spec is based on the format strings used by Redshift in its [COPY command](https://docs.aws.amazon.com/redshift/latest/dg/r_DATEFORMAT_and_TIMEFORMAT_strings.html).

However, those particular format string semantics as documented are used only by COPY, not by UNLOAD.  

The spec says this:

> The seconds (SS) field also supports fractional seconds up to a microsecond level of detail.

This behavior is very friendly on input, but on output it can lead to expected precision - especially when processed by tools like Pandas/Python strftime() that don't have the capability to silently drop the fractional component when it is zero.

As of this writing, Records Mover's Pandas-based output uses fractional seconds for datetime/datetimetz values, but not for timeonly values, which is certainly unexpected.

Most likely approaches to fix:
* A: Keep current behavior exactly and document it in the spec as expected.
* B: Introduce a new timepart string on output that implies seconds without fractional seconds; leave SS implying fractional seconds and change current Pandas behavior around timeonly values.
* C: Introduce a new timepart string on output that implies seconds with fractional seconds; change SS on output to give only whole seconds; change current Pandas behavior around datetime and datetimetz values.

**Comment by cwegrzyn** [comment]
Consolidating some notes from an old slack conversation on this topic:

I’m not sure if this helps clarify anything at all, because I’m still wrapping my head around it. But I started by thinking about principles and two I can think of are: 1. we never lose available precision (unless the user goes out of their way to tell us to drop it) 2. the written specification of a file unambiguously describes what is in it (with the understanding that a consumer of the spec can always adapt at runtime-- that is, there is no requirement that we can pass the format string directly to redshift without modification)

I think that #2 (which is maybe two separate principles) alone implies that we should go with option C?

UNLOAD from Redshift includes fractional seconds. So if we had any existing records directories with a schema including "SS" as the time format but "SS.microseconds" in the file, we’d have to deal with how we load those old files if we’re expecting the format to accurately represent what is in the file.

We're not sure we have a lot of existing records directories, so maybe it's a non-issue. Could we also consider bumping a schema version? Is it worth it? I guess Redshift will never be strict on load, which also makes it a non-issue when loading to Redshift. Maybe we can make other targets equally flexible on input. If the raw file has the extra precision, it doesn't feel like a problem to load it-- after all, the point of the schema isn't to coerce the data, but to say what it actually is so it can be parsed effectively.

(And tagging in the new Vince at @apiology)
